name: LuSetHome
version: '${project.version}'
main: me.notshiya.lusethome.LuSetHome
api-version: '1.20'
author: notshiya
description: A simple plugin that allows players to set their home and teleport to it.
commands:
  sethome:
    description: Set your home.
    usage: /sethome
  home:
    description: Teleport to your home.
    usage: /home
  deletehome:
    description: Delete your home.
    usage: /delhome